# Generated by Django 4.2.7 on 2023-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_calib_in_TBC', models.CharField(max_length=50)),
                ('name_calib_rus', models.CharField(max_length=50)),
                ('SC', models.CharField(choices=[('SC63', 'SC63'), ('MSK', 'MSK')], max_length=4)),
                ('zone', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=2)),
            ],
        ),
    ]
