# Generated by Django 4.2.7 on 2023-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate_system',
            name='zone',
            field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('Not Zone', 'Not Zone')], max_length=8),
        ),
    ]
