# Generated by Django 4.2.7 on 2023-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coordinate_system_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_file')),
                ('separator', models.CharField(choices=[('Пробел', ' '), ('Табуляция', '   '), ('Запятая', ','), ('Точка с запятой', ';')], max_length=25)),
                ('time_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
