# Generated by Django 4.2.7 on 2023-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_file',
            old_name='file',
            new_name='file_in',
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='separator',
            field=models.CharField(choices=[(' ', 'Пробел'), ('   ', 'Табуляция'), (',', 'Запятая'), (';', 'Точка с запятой')], max_length=25),
        ),
    ]
